name: "Main"

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: Test on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15"
          check-latest: true
      - run: node --version
      - run: yarn --version
      - run: yarn
      - run: pwd
      - run: ls -la
      - run: yarn ts-node ./examples/test.ts
      # - run: yarn ts-node-dev ./examples/test.ts
      # - run: cd examples && yarn ts-node ./file-system.ts
